### PR TITLE
Upgrade stellar-sdk

### PR DESCRIPTION
**Pull request by msfeldstein**
sdk was getting out of date, new protocol 13 changes make this immediately necessary

### CODE REVIEW

**Comment by tomerweller** [comment]
Can we limit this PR to just updating the stellar sdk? The scope of this seems a bit extensive

**Comment by msfeldstein** [comment]
I can try but stellar-sdk has a lot of dependencies that get updated, let me see

**Comment by tomerweller** [comment]
oh if it's the sdk's dependencies then never mind. I mistakenly thought that npm somehow opportunistically updated a bunch of unrelated packages

**Comment by msfeldstein** [comment]
i ran `yarn upgrade stellar-sdk` but let me verify that that second
argument is actually used

**Comment by msfeldstein** [comment]
yeah this is just a long dependency chain

**Pull request merged**
