### PR TITLE
Added deprecation warning

### PR DESCRIPTION
**Pull request by JakeUrban**
We should only merge this when we're ready to announce it.

### CODE REVIEW

**Comment by JakeUrban** [comment]
Screen Shot 2020-11-24 at 4 01 44 PM

**Comment by JakeUrban** [comment]
@morleyzhi thanks for adding that feature for Settle. That change made sense because the demo-wallet.stellar.org app doesn't have the same "Config" menu, although that should be added if we want to make it a proper debug tool (@Zagan202).

**Review by Zagan202 — APPROVED** [review]
LGTM
The next step is to move it to `stellar-deprecated` 
https://github.com/stellar-deprecated
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

However I'm not sure on the transferring timeline we're aiming for

**Comment by JakeUrban** [comment]
I'm not familiar with the process of transferring the repo, but I think thats far off.

**Comment by Zagan202** [comment]
Just remembered as part of the demo-wallet road map we need to also direct traffic from sep24.stellar.org traffic to demo-wallet.stellar.org

**Comment by JakeUrban** [comment]
Right, but not yet, otherwise there would be no point in putting the deprecation warning

Once we're 100% confident the demo wallet can provide the same functionality and the warning has been up for some time, then we can redirect the traffic and transfer the repository to the stellar-deprecated repo.

**Comment by JakeUrban** [comment]
Ok, @Zagan202 I think I'm going to merge this. Any reason not to?

**Pull request merged**
